apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: micrologger-tester
  namespace: testing
  labels:
    app: micromicrologger-testerer
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: micrologger-tester
    spec:
      containers:
      - name: micrologger-tester 
        image: quay.io/giantswarm/micrologger-tester:latest
      restartPolicy: Always