apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logger-test
  namespace: testing
  labels:
    app: logger-test
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: logger-test
    spec:
      containers:
      - name: logger-test 
        image: quay.io/giantswarm/micrologger-tester:latest
      restartPolicy: Always